[package]
name = "ditto"
authors = ["Dylan DiBeneditto <dibenedittod@gmail.com>"]
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "My programming language"
readme = "README.md"

[[bin]]
name = "ditto"
path = "src/cli.rs"

[dependencies]
